### ISSUE TITLE
Error in build_kernel.sh

### ISSUE THREAD

**Issue by ziXet** [RobertCNelson/armv7_devel#1]
I'm using v3.15.x-vybrid-armv7 branch and get the following error in compiling linux:

/home/user/armv7_devel/KERNEL/arch/arm/boot/compressed/Makefile:193: recipe for target 'arch/arm/boot/compressed/piggy.lzo' failed
make[2]: **\* [arch/arm/boot/compressed/piggy.lzo] Error 1
/home/user/armv7_devel/KERNEL/arch/arm/boot/Makefile:52: recipe for target 'arch/arm/boot/compressed/vmlinux' failed
make[1]: **\* [arch/arm/boot/compressed/vmlinux] Error 2
/home/user/armv7_devel/KERNEL/arch/arm/Makefile:304: recipe for target 'zImage' failed
make: **\* [zImage] Error 2
make: **\* Waiting for unfinished jobs....

The error appears after pulling the latest changes.

**Comment by RobertCNelson** [comment]
Which distro is this? Using lzo speeds up the boot process, but it's a relatively newer compression. In debian this is provided by the lzop package.

**Comment by ziXet** [comment]
I'm using Arch Linux. It's been solved after install lzop package.
